### ISSUE TITLE
تجهيز المكتب الرسمي

### ISSUE THREAD

**Issue by mehmetashki** [zadmedia/management-todo#12]
تجهيز المكتب الرسمي مشان المقابلات

**Comment by mehmetashki** [comment]
اشتريت 10 لفات ورق الجدران  100ليرة
أخذت 2 مقاعد وطاولة 850 ليرة

**Comment by amersabag** [comment]
متى التركيب؟

**Comment by mehmetashki** [comment]
بس نخلص من دهان السقف اليوم او غدا

**Comment by amersabag** [comment]
انتهى والحمد لله
