### ISSUE TITLE
المحامي له عندنا 200 ليرة تركية

### ISSUE THREAD

**Issue by amersabag** [zadmedia/management-todo#13]
وذلك عن عمل الموظفة عندهم يوم العطلة أثناء المقابلات. ويجب الذهاب لعنده وتسليمه المبلغ أو تحويله بالبنك.

**Comment by mehmetashki** [comment]
شيخ عامر مو انت تعطيني200  وانا عطيتو للمحاسب
خالصين من هذا الموضوع

**Comment by amersabag** [comment]
آه، صحيح، والله نسيت.
