### ISSUE TITLE
موعد إقامتي

### ISSUE THREAD

**Issue by amersabag** [zadmedia/management-todo#2]
أظن بأننا انتظرنا بما فيه الكفاية، يجب أن يستعجل المحاسب في موضوع موعد الحصول على الإقامة

**Comment by mehmetashki** [comment]
موعد الإقامة   05.02.2015  الساعة  09:00  
العنوان باغجلار امنيات

يجب ان تحضر معك
4 صور
الاصل جواز السفر 
صورة جواز السفر

**Comment by amersabag** [comment]
سأقوم بتغيير الموعد ليكون في ايسينيورت ولإقامة سياحية

**Comment by amersabag** [comment]
بانتظار عقد السكن الخاص بالإقامة من قبل المحاسب
