### ISSUE TITLE
البحث عن اشتراك إنترنت ثالث

### ISSUE THREAD

**Issue by amersabag** [zadmedia/management-todo#3]
البحث عن شركة إنترنت ثالثة للمكتب، ولماذا لا نطلب الإنترنت مرة أخرى من تي تي نت نفسها؟

**Comment by amersabag** [comment]
هذا الموضوع أيضا مهم أرجو أن لا تنساه

**Comment by mehmetashki** [comment]
ان شاءالله

**Comment by amersabag** [comment]
هل حصل شيء في هذا الموضوع؟

**Comment by mehmetashki** [comment]
D-Smart للأسف  لايوجد لديهم علبة فارغة ايضا
