### ISSUE TITLE
اشتراك تورك تيليكوم

### ISSUE THREAD

**Issue by amersabag** [zadmedia/management-todo#4]
بانتظار موافقة تورك تيليكوم على الإنترنت حتى نحصل على كلمة السر

**Comment by mehmetashki** [comment]
للأسف اليوم جتني الرسالة من تورك نت  
(لا يمكننا بتنفيذ طلبكم حزمة كاملة الاتصالات الخاصة بك)

**Comment by amersabag** [comment]
أرجو أن تتصل بهم وتسألهم عن السبب

**Comment by mehmetashki** [comment]
اتصلت وقالوا لا يوجد عندهم خدمة انترنت كافية في المكان
